# Chapter 1: The Importance of Data Visualization and Data Exploration

Ở chương này chúng ta sẽ thực hiện các bài luyện tập để làm quen với những toán tử cơ bản trong `NumPy` và `Pandas`.

Bài làm này chỉ tập trung vào 6 Activities vì hai bài Exercise 01, 02 đã có đáp án ngay sau câu hỏi.

## Activity 01: Use NumPy to compute the Mean, Median, and Variance

Đầu tiên, chúng ta cần củng cố lại các kỹ năng được học về các dùng NumPy để thực hiện một số tính toán đơn giản trong tập dữ liệu từ file `normal_distribution.csv`.


#### Loading the dataset

In [77]:
# importing the necessary dependencies
import numpy as np

Chúng ta dùng hàm **genfromtxt** trong thư viện `NumPy` để đọc dữ liệu từ file.

Hàm này rất hữu ích khi ta cần làm việc với dữ liệu dạng bảng trong các tệp văn bản như CSV, TSV hoặc các tệp văn bản tương tự khác.

In [157]:
# loading the Dataset
dataset = np.genfromtxt('./data/normal_distribution.csv', delimiter=',')

Đảm bảo rằng dữ liệu đã được truyền vào biến `dataset` bằng cách truy xuất các phần tử trong `dataset` và đối chiếu.

In [79]:
dataset[0:5]

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 , 106.1472841 ,  95.08715803],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732]])

#### Tính trung bình

Dưới đây là các tính toán về giá trị trung bình của dữ liệu thông qua toán tử `mean` được cung cấp bởi thư viện.

In [80]:
# Tính mean ở dòng thứ 3:
np.mean(dataset[2])

100.20466135250001

In [81]:
# Tính mean ở cột cuối cùng:
np.mean(dataset[:,-1])

100.4404927375

In [82]:
# Tính giá trị trung bình giao điểm của 3 hàng đầu tiên và 3 cột đầu tiên
np.mean(dataset[0:3, 0:3])

97.87197312333333

#### Tính trung vị

Tương tự bài trên, ở đây chúng ta tìm giá trị trung bình của dữ liệu thông qua toán tử `median` được cung cấp bởi `NumPy`.

In [83]:
# Tính median ở dòng cuối cùng
np.median(dataset[-1])

99.18748092

In [84]:
# Tính median ở 3 cột cuối
np.median(dataset[:, -3:])

99.47332349999999

In [85]:
# Tính median cho mỗi dòng
np.median(dataset, axis=1)

array([ 98.77910163,  97.17512034,  98.58782879, 100.68449836,
       101.00170737,  97.76908825, 101.85002253, 100.04756697,
       102.24292555,  99.59514997, 100.4955753 ,  99.8860714 ,
        99.00647994,  98.67276177, 102.44376222,  96.61933565,
       104.0968893 , 100.72023043,  98.70877396,  99.75008654,
       104.89344428, 101.00634942,  98.30543801,  99.18748092])

---

#### Tính phương sai

Thư viện `NumPy` cũng cung cấp toán tử tìm phương sai - `var`

In [86]:
# Phương sai trên mỗi cột: 
np.var(dataset, axis=0)

array([23.64757465, 29.78886109, 20.50542011, 26.03204443, 28.38853175,
       19.09960817, 17.67291174, 16.17923204])

In [87]:
# Phương sai của phần giao giữa hai dòng cuối với 2 cột đầu
np.var(dataset[-2:, :2])

4.674691991769191

***Ghi chú:***
- axis =  0 sẽ truy xuất các phần tử trên tất cả các ROWS trong mỗi CỘT
- axis = 1 sẽ truy xuất các phần tử trên tất cả các CỘT trong mỗi ROW

#### Tính độ lệch chuẩn 

Dùng toán tử `std` - standard deviation trong `NumPy`

In [88]:
np.std(dataset)

4.838197554269257

### ***Bài học rút ra:***
Việc xử lý các phần tử gần như tuân theo quy tắc truy xuất của cấu trúc mảng trong lập trình.

Dưới đây là một số kỹ thuật truy xuất phần tử trên mảng:

**Indexing**

Đối với NumPy, chúng ta có thể xử lý số liệu bằng cách đưa nó về mảng n chiều (ndarrays). Cao cấp hơn, chúng ta dùng cấu trúc dữ liệu `list` trong Python.

```
dataset[0] # index ở vị trí ngoài cùng (đầu tiên) của dữ liệu 1 chiều 
dataset[-1] # index theo thứ tự đảo ngược ở chiều ngoài cùng.
dataset[1, 1] # index phần tử đơn lẻ trong dữ liệu 2 chiều 
dataset[-1, -1] # index thứ tự đảo ngược ở dữ liệu 2 chiều
```

**Slicing**

Kỹ thuật `cắt lát` cũng được hiệu chỉnh trong `list`, kỹ thuật này rất hữu dụng khi thao tác với những bộ dữ liệu lớn
```
dataset[1:3] # dòng 1 và 2
dataset[:2, :2] # tập hợp con 2x2 của dữ liệu
dataset[-1, ::-1] # đảo ngược các phần tử ở dòng cuối cùng
dataset[-5:-1, :6:2] # ở 4 hàng cuối cùng, mọi phần tử khác lên đến index 6
```
**Splitting**

Kỹ thuật `chia nhỏ dữ liệu` hữu dụng trong các đồ thị chỉ yêu cầu vẽ một nửa dữ liệu kiểu chuỗi thời gian để tách dữ liệu ra kiểm tra và train cho các thuật toán ML.

Có hai cách để chia nhỏ dữ liệu, theo chiều ngang và chiều dọc. 
- Chia ngang có thể được thực hiện bằng phương pháp `hsplit`.
- Tách dọc có thể được thực hiện bằng phương pháp `vsplit`:
```
np.hsplit(dataset, (3)) # Chia theo chiều ngang thành 3 danh sách bằng nhau
np.vsplit(dataset, (2)) # Chia theo chiều dọc thành 2 danh sách bằng nhau
```
**Iterating**

`Phép lặp` là cấu trúc dữ liệu trong NumPy. Nó lần lượt đi qua toàn bộ danh sách dữ liệu, truy cập mọi phần tử đơn trong ndarray một lần. Trong những trường hợp dữ liệu có nhiều chiều, sự lặp trở nên rất phức tạp.

`nditer` là một đối tượng iterator đa chiều lặp lại trên một số mảng nhất định:
```
# Lặp lại trên toàn bộ tập dữ liệu (mỗi giá trị trong mỗi hàng)
for x in np.nditer(dataset):
print(x)
```

`ndenumerate` sẽ cung cấp cho chúng ta chính xác chỉ số này, do đó trả về (0, 1) cho giá trị thứ hai trong hàng đầu tiên:

```
#Lặp lại trên toàn bộ tập dữ liệu với các chỉ số khớp với vị trí trong tập dữ liệu
for index, value in np.ndenumerate(dataset):
print(index, value)
```

Các kỹ thuật này sẽ được học kỹ và thực hành ở **Activity 02**.

------------------------------------

## Activity 02: Indexing, Slicing, and Iterating

Giả sử rằng:

Khách hàng muốn chúng ta chứng minh rằng tập dữ liệu đang có là một phân phối "đẹp" với mean ~ 100.
Và họ yêu cầu ta chạy vài kiểm chứng trên các phần nhỏ để đảm bảo rằng họ không dính vào trường hợp có dữ liệu không mang ý nghĩa.

Chúng ta hãy thử dùng các kỹ thuật đã nêu để xử lý vấn đề nhé!

#### Indexing

In [125]:
# Lấy giá trị của dòng thứ 2 của tập dữ liệu 
val = dataset[1]
print(val)

[ 92.02628776  97.10439252  99.32066924  97.24584816  92.9267508
  92.65657752 105.7197853  101.23162942]


In [126]:
np.mean(val)

97.27899259

In [120]:
# dòng cuối cùng của tập dữ liệu 
val = dataset[-1]
print(val)

[ 94.11176915  99.62387832 104.51786419  97.62787811  93.97853495
  98.75108352 106.05042487 100.07721494]


In [122]:
# Lấy mean 
np.mean(val)

99.34233100624999

In [127]:
# Lấy giá trị đầu tiên của dòng hai --> i[1][0] 
dataset[1][0]

92.02628776

In [128]:
np.mean(dataset[1][0])

92.02628776

In [130]:
# Lấy mean giá trị cuối cùng từ dòng hai tới dòng cuối
val = dataset[-2, -1]
np.mean(val)


103.83852459

---

#### Slicing

In [131]:
# cắt phần giao của 4 phần tử của hai hàng đầu tiên và hai cột đầu tiên
sub_matrix = dataset[0:2, 0:2]
np.mean(sub_matrix)

98.07963072250001

In [132]:
# Lấy mean mọi phần tử thứ hai của hàng thứ năm
select = dataset[4, ::2]
np.mean(select)

98.915396795

In [135]:
# Đảo ngược hai hàng đầu tiên của data
reversed_first_two_rows = dataset[:2, ::-1]
np.mean(reversed_first_two_rows)

98.7283200575

**Nhận xét**: các tập dữ liệu nhỏ được chia tách từ dataset có giá trị trung bình loanh quanh 100. 

Thông thường, khi làm việc với dữ liệu thống kê, người ta thường mong muốn rằng giá trị trung bình của tập dữ liệu sẽ ổn định và gần giá trị trung bình mong đợi.

Do đó, chúng ta có căn cứ để khẳng định với khách hàng rằng tập dữ liệu mà họ đang nắm có phân phối "đẹp"

#### Splitting

Nếu cần một tập dữ liệu nhỏ hơn, chúng ta cũng có thể sử dụng tính năng chia tách để phân chia tập dữ liệu của mình một cách hiệu quả.

Giả sử tập dữ liệu của chúng ta chia như sau: 

```
1, 2, 3, 4, 5, 6          1, 2     3, 4    5, 6          1, 2  
3, 2, 1, 5, 4, 6    =>    3, 2     1, 5    4, 6    =>    3, 2    =>    1, 2
5, 3, 1, 2, 4, 3          5, 3     1, 2    4, 3                        3, 2
1, 2, 2, 4, 1, 5          1, 2     2, 4    1, 5          5, 3
                                                         1, 2
```

Có nghĩa là nó được chia thành 3 phần bằng nhau và sau đó lại lấy phần đầu của lần chia đầu tiên chia thành 2 nửa nhỏ.

Việc phân chia dữ liệu theo chiều ngang có thể được thực hiện bằng phương pháp hsplit. 

Tuy nhiên, ta không thể phân chia tập dữ liệu với số lát = 3 như ví dụ, nó sẽ báo lỗi như sau:

In [161]:
# splitting up our dataset horizontally on indices one third and two thirds
hor_splits = np.hsplit(dataset,(3))

ValueError: array split does not result in an equal division

Lỗi này cho biết số lượng phần cần chia thành các mảng con đang không bằng nhau.

Để sửa lỗi này, bạn cần chỉnh sửa số lượng phần hoặc chỉ mục bạn đang sử dụng để chia mảng sao cho chia đều.

In [162]:
hor_splits = np.hsplit(dataset,(8))
print("Dataset", dataset.shape)
print("Subset", hor_splits[0].shape)

Dataset (24, 8)
Subset (24, 1)


Bây giờ chúng ta cần chia phần ba phần đầu tiên thành hai phần bằng nhau theo chiều dọc. 

Dùng `vsplit`:

In [163]:
# splitting up our dataset vertically on index 2
ver_splits = np.vsplit(hor_splits[0],(2))

In [164]:
# requested subsection of our dataset which has only half the amount of rows and only a third of the columns
print("Dataset", dataset.shape)
print("Subset", ver_splits[0].shape)

Dataset (24, 8)
Subset (12, 1)


#### Iterating

Lặp là kỹ thuật khá quen thuộc đối với lập trình.

Bây giờ chúng ta sẽ dùng vòng lặp để "ghé nhà" từng phần tử của list và "hỏi thăm" giá trị của chúng ra sao!

Ở cách này chúng ta khá "chày cối" trong việc truy xuất phần tử của mảng nhiều chiều bằng `nditer`. 

Nói như thế là bởi vì dataset mà chúng ta có là một mảng 2 chiều nhưng chúng ta đang truy xuất thuần túy của mảng một chiều nên các giá trị được in ra như một danh sách khá là khó biết được vị trí của phần tử chính xác là nơi nào.

In [ ]:
# iterating over whole dataset (each value in each row)
current_ind = 0
for x in np.nditer(dataset):
    print(x, current_ind)
    current_ind += 1

99.14931546 0
104.03852715 1
107.43534677 2
97.85230675 3
98.74986914 4
98.80833412 5
96.81964892 6
98.56783189 7
92.02628776 8
97.10439252 9
99.32066924 10
97.24584816 11
92.9267508 12
92.65657752 13
105.7197853 14
101.23162942 15
95.66253664 16
95.17750125 17
90.93318132 18
110.18889465 19
98.80084371 20
105.95297652 21
98.37481387 22
106.54654286 23
91.37294597 24
100.96781394 25
100.40118279 26
113.42090475 27
105.48508838 28
91.6604946 29
106.1472841 30
95.08715803 31
101.20862522 32
103.5730309 33
100.28690912 34
105.85269352 35
93.37126331 36
108.57980357 37
100.79478953 38
94.20019732 39
102.80387079 40
98.29687616 41
93.24376389 42
97.24130034 43
89.03452725 44
96.2832753 45
104.60344836 46
101.13442416 47
106.71751618 48
102.97585605 49
98.45723272 50
100.72418901 51
106.39798503 52
95.46493436 53
94.35373179 54
106.83273763 55
96.02548256 56
102.82360856 57
106.47551845 58
101.34745901 59
102.45651798 60
98.74767493 61
97.57544275 62
92.5748759 63
105.30350449 64
92.87730812

Để đảm bảo rằng phần tử có index dòng - cột rõ ràng, chúng ta dùng ndenumerate khi lặp trên mảng nhiều chiều:

In [107]:
# iterating over whole dataset with indices matching the position in the dataset
for index, value in np.ndenumerate(dataset):
    print(index, value)

(0, 0) 99.14931546
(0, 1) 104.03852715
(0, 2) 107.43534677
(0, 3) 97.85230675
(0, 4) 98.74986914
(0, 5) 98.80833412
(0, 6) 96.81964892
(0, 7) 98.56783189
(1, 0) 92.02628776
(1, 1) 97.10439252
(1, 2) 99.32066924
(1, 3) 97.24584816
(1, 4) 92.9267508
(1, 5) 92.65657752
(1, 6) 105.7197853
(1, 7) 101.23162942
(2, 0) 95.66253664
(2, 1) 95.17750125
(2, 2) 90.93318132
(2, 3) 110.18889465
(2, 4) 98.80084371
(2, 5) 105.95297652
(2, 6) 98.37481387
(2, 7) 106.54654286
(3, 0) 91.37294597
(3, 1) 100.96781394
(3, 2) 100.40118279
(3, 3) 113.42090475
(3, 4) 105.48508838
(3, 5) 91.6604946
(3, 6) 106.1472841
(3, 7) 95.08715803
(4, 0) 101.20862522
(4, 1) 103.5730309
(4, 2) 100.28690912
(4, 3) 105.85269352
(4, 4) 93.37126331
(4, 5) 108.57980357
(4, 6) 100.79478953
(4, 7) 94.20019732
(5, 0) 102.80387079
(5, 1) 98.29687616
(5, 2) 93.24376389
(5, 3) 97.24130034
(5, 4) 89.03452725
(5, 5) 96.2832753
(5, 6) 104.60344836
(5, 7) 101.13442416
(6, 0) 106.71751618
(6, 1) 102.97585605
(6, 2) 98.45723272
(6, 3) 100.724

## Activity 03: Filtering, Sorting, and Reshaping

Vẫn dùng dataset cũ chúng ta có các phần thực hành như sau:

#### Filtering

In [141]:
# Lọc các giá trị lớn hơn 105
filter_1 = dataset[dataset > 105]
print(filter_1)

[107.43534677 105.7197853  110.18889465 105.95297652 106.54654286
 113.42090475 105.48508838 106.1472841  105.85269352 108.57980357
 106.71751618 106.39798503 106.83273763 106.47551845 105.30350449
 106.03868807 110.44484313 106.6471081  105.0320535  107.02874163
 105.07475277 107.22482426 107.19119932 108.09423367 109.40523174
 106.11454989 106.57052697 105.13668343 105.37011896 105.86078488
 106.89005002 106.57364584 107.40064604 106.38276709 106.46476468
 110.43976681 105.02389857 106.05042487]


In [144]:
# Lọc các giá trị nằm trong khoảng từ 90 đến 95
filter_2 = dataset[(dataset > 90) & (dataset < 95)]
print(filter_2)

[92.02628776 92.9267508  92.65657752 90.93318132 91.37294597 91.6604946
 93.37126331 94.20019732 93.24376389 94.35373179 92.5748759  92.87730812
 93.87155456 92.75048583 91.32093303 92.0108226  93.18884302 93.83969256
 94.5081787  94.59300658 93.04610867 91.6779221  94.76253572 94.57421727
 94.11176915 93.97853495]


In [146]:
# Hoặc dùng extract của np như sau:
filter_2 = np.extract((dataset > 90) & (dataset < 95), dataset)
print(filter_2)

[92.02628776 92.9267508  92.65657752 90.93318132 91.37294597 91.6604946
 93.37126331 94.20019732 93.24376389 94.35373179 92.5748759  92.87730812
 93.87155456 92.75048583 91.32093303 92.0108226  93.18884302 93.83969256
 94.5081787  94.59300658 93.04610867 91.6779221  94.76253572 94.57421727
 94.11176915 93.97853495]


In [150]:
# Lọc ra các chỉ số chứa giá trị khác nhau < (1,100)
rows, cols = np.where(abs(dataset - 100) < 1)
filter_ind = [[rows[index], cols[index]] for (index, _) in np.ndenumerate(rows)]
print(filter_ind)

[[0, 0], [1, 2], [3, 1], [3, 2], [4, 2], [4, 6], [6, 3], [8, 5], [10, 1], [10, 3], [10, 5], [13, 0], [13, 4], [13, 7], [14, 3], [14, 5], [16, 1], [16, 6], [17, 2], [17, 3], [18, 7], [20, 4], [21, 0], [21, 4], [21, 5], [22, 2], [23, 1], [23, 7]]


#### Sorting

In [153]:
# Sắp xếp giá trị theo từng dòng
row_sorted = np.sort(dataset)
print(row_sorted)

[[ 96.81964892  97.85230675  98.56783189  98.74986914  98.80833412
   99.14931546 104.03852715 107.43534677]
 [ 92.02628776  92.65657752  92.9267508   97.10439252  97.24584816
   99.32066924 101.23162942 105.7197853 ]
 [ 90.93318132  95.17750125  95.66253664  98.37481387  98.80084371
  105.95297652 106.54654286 110.18889465]
 [ 91.37294597  91.6604946   95.08715803 100.40118279 100.96781394
  105.48508838 106.1472841  113.42090475]
 [ 93.37126331  94.20019732 100.28690912 100.79478953 101.20862522
  103.5730309  105.85269352 108.57980357]
 [ 89.03452725  93.24376389  96.2832753   97.24130034  98.29687616
  101.13442416 102.80387079 104.60344836]
 [ 94.35373179  95.46493436  98.45723272 100.72418901 102.97585605
  106.39798503 106.71751618 106.83273763]
 [ 92.5748759   96.02548256  97.57544275  98.74767493 101.34745901
  102.45651798 102.82360856 106.47551845]
 [ 92.87730812 100.85447132 101.2226037  101.29326772 103.19258339
  104.40518318 105.30350449 106.03868807]
 [ 92.75048583  93.

> **Note:**   
Theo mặc định, việc sắp xếp sẽ luôn được thực hiện dọc theo trục cuối cùng. Trong trường hợp của chúng ta, axis = 1, cho nên sẽ sắp xếp theo dòng.

In [155]:
# Sắp xếp giá trị theo từng cột
col_sorted = np.sort(dataset, axis=0)
print(col_sorted)

[[ 91.37294597  88.80221141  90.93318132  93.18884302  85.98839623
   91.6604946   91.32093303  92.5748759 ]
 [ 92.02628776  91.6779221   93.24376389  94.59300658  89.03452725
   92.65657752  93.04610867  94.20019732]
 [ 94.11176915  92.0108226   93.83969256  96.74630281  92.75048583
   95.19184343  94.35373179  94.76253572]
 [ 95.65982034  92.87730812  94.5081787   97.24130034  92.9267508
   95.46493436  96.50342927  95.08715803]
 [ 95.66253664  93.87155456  97.75887636  97.24584816  93.37126331
   95.62359311  96.81964892  95.85284217]
 [ 96.02548256  94.57421727  98.45723272  97.62787811  93.97853495
   96.2832753   96.89244283  97.59572169]
 [ 96.10020311  95.17750125  99.32066924  97.65393524  95.93799169
   96.34622848  96.96851209  98.00253006]
 [ 96.76814836  96.59385486  99.57859892  97.85230675  98.29243952
   96.5937781   97.57544275  98.07122664]
 [ 96.78266211  97.10439252 100.28690912  99.4889538   98.61325194
   98.65912661  97.94046856  98.56783189]
 [ 97.21315663  98.2

In [154]:
# lấy chỉ số vị trí cho mỗi hàng
index_sorted = np.argsort(dataset)
print(index_sorted)

[[6 3 7 4 5 0 1 2]
 [0 5 4 1 3 2 7 6]
 [2 1 0 6 4 5 7 3]
 [0 5 7 2 1 4 6 3]
 [4 7 2 6 0 1 3 5]
 [4 2 5 3 1 7 0 6]
 [6 5 2 3 1 4 0 7]
 [7 0 6 5 3 4 1 2]
 [1 5 6 4 2 3 0 7]
 [4 1 6 3 2 5 7 0]
 [7 6 5 1 3 0 4 2]
 [4 3 0 7 2 5 6 1]
 [4 6 5 0 7 3 2 1]
 [1 3 6 2 7 0 4 5]
 [2 5 3 4 6 0 7 1]
 [1 2 3 5 6 7 4 0]
 [0 6 1 2 7 4 5 3]
 [5 6 3 2 0 4 1 7]
 [6 5 1 0 7 3 2 4]
 [1 0 6 4 3 2 5 7]
 [7 4 2 5 6 1 0 3]
 [7 0 5 4 6 1 2 3]
 [1 5 0 6 4 2 7 3]
 [4 0 3 5 1 7 2 6]]


#### Combining

In [166]:
# Tách dữ liệu như trong activity 3
thirds = np.hsplit(dataset, (8))
halfed_first = np.vsplit(thirds[0], (2))
halfed_first[0]

array([[ 99.14931546],
       [ 92.02628776],
       [ 95.66253664],
       [ 91.37294597],
       [101.20862522],
       [102.80387079],
       [106.71751618],
       [ 96.02548256],
       [105.30350449],
       [110.44484313],
       [101.3514185 ],
       [ 97.21315663]])

In [168]:
# thêm nửa sau của cột đầu tiên vào dữ liệu
first_col = np.vstack([halfed_first[0], halfed_first[1]])
print(first_col)

[[ 99.14931546]
 [ 92.02628776]
 [ 95.66253664]
 [ 91.37294597]
 [101.20862522]
 [102.80387079]
 [106.71751618]
 [ 96.02548256]
 [105.30350449]
 [110.44484313]
 [101.3514185 ]
 [ 97.21315663]
 [ 95.65982034]
 [100.39303522]
 [103.1521596 ]
 [106.11454989]
 [ 96.78266211]
 [101.86186193]
 [ 97.49594839]
 [ 96.76814836]
 [106.89005002]
 [ 99.80873105]
 [ 96.10020311]
 [ 94.11176915]]


In [170]:
# thêm cột thứ hai vào tập dữ liệu kết hợp
first_second_col = np.hstack([first_col, thirds[1]])

In [171]:
# thêm vào tập dữ liệu kết hợp cột thứ ba
full_data = np.hstack([first_second_col, thirds[2]])
print(full_data)

[[ 99.14931546 104.03852715 107.43534677]
 [ 92.02628776  97.10439252  99.32066924]
 [ 95.66253664  95.17750125  90.93318132]
 [ 91.37294597 100.96781394 100.40118279]
 [101.20862522 103.5730309  100.28690912]
 [102.80387079  98.29687616  93.24376389]
 [106.71751618 102.97585605  98.45723272]
 [ 96.02548256 102.82360856 106.47551845]
 [105.30350449  92.87730812 103.19258339]
 [110.44484313  93.87155456 101.5363647 ]
 [101.3514185  100.37372248 106.6471081 ]
 [ 97.21315663 107.02874163 102.17642112]
 [ 95.65982034 107.22482426 107.19119932]
 [100.39303522  92.0108226   97.75887636]
 [103.1521596  109.40523174  93.83969256]
 [106.11454989  88.80221141  94.5081787 ]
 [ 96.78266211  99.84251605 104.03478031]
 [101.86186193 103.61720152  99.57859892]
 [ 97.49594839  96.59385486 104.63817694]
 [ 96.76814836  91.6779221  101.79132774]
 [106.89005002 106.57364584 102.26648279]
 [ 99.80873105 101.63973121 106.46476468]
 [ 96.10020311  94.57421727 100.80409326]
 [ 94.11176915  99.62387832 104.51

#### Reshaping

Trong AI, việc định hình `reshape` lại dữ liệu rất cần thiết.

Thông thường chúng ta thường gặp cách trường hợp sau: 
- reshape tất cả các giá trị thành danh sách một chiều
- reshape data thành một ma trận có 2 cột

In [173]:
# reshape tập dữ liệu thành một list duy nhất
single_list = np.reshape(dataset, (1, -1))
print(single_list)

[[ 99.14931546 104.03852715 107.43534677  97.85230675  98.74986914
   98.80833412  96.81964892  98.56783189  92.02628776  97.10439252
   99.32066924  97.24584816  92.9267508   92.65657752 105.7197853
  101.23162942  95.66253664  95.17750125  90.93318132 110.18889465
   98.80084371 105.95297652  98.37481387 106.54654286  91.37294597
  100.96781394 100.40118279 113.42090475 105.48508838  91.6604946
  106.1472841   95.08715803 101.20862522 103.5730309  100.28690912
  105.85269352  93.37126331 108.57980357 100.79478953  94.20019732
  102.80387079  98.29687616  93.24376389  97.24130034  89.03452725
   96.2832753  104.60344836 101.13442416 106.71751618 102.97585605
   98.45723272 100.72418901 106.39798503  95.46493436  94.35373179
  106.83273763  96.02548256 102.82360856 106.47551845 101.34745901
  102.45651798  98.74767493  97.57544275  92.5748759  105.30350449
   92.87730812 103.19258339 104.40518318 101.29326772 100.85447132
  101.2226037  106.03868807 110.44484313  93.87155456 101.536364

In [174]:
# reshaping thành ma trận có 2 cột
res = dataset.reshape(-1, 2)
print(res)

[[ 99.14931546 104.03852715]
 [107.43534677  97.85230675]
 [ 98.74986914  98.80833412]
 [ 96.81964892  98.56783189]
 [ 92.02628776  97.10439252]
 [ 99.32066924  97.24584816]
 [ 92.9267508   92.65657752]
 [105.7197853  101.23162942]
 [ 95.66253664  95.17750125]
 [ 90.93318132 110.18889465]
 [ 98.80084371 105.95297652]
 [ 98.37481387 106.54654286]
 [ 91.37294597 100.96781394]
 [100.40118279 113.42090475]
 [105.48508838  91.6604946 ]
 [106.1472841   95.08715803]
 [101.20862522 103.5730309 ]
 [100.28690912 105.85269352]
 [ 93.37126331 108.57980357]
 [100.79478953  94.20019732]
 [102.80387079  98.29687616]
 [ 93.24376389  97.24130034]
 [ 89.03452725  96.2832753 ]
 [104.60344836 101.13442416]
 [106.71751618 102.97585605]
 [ 98.45723272 100.72418901]
 [106.39798503  95.46493436]
 [ 94.35373179 106.83273763]
 [ 96.02548256 102.82360856]
 [106.47551845 101.34745901]
 [102.45651798  98.74767493]
 [ 97.57544275  92.5748759 ]
 [105.30350449  92.87730812]
 [103.19258339 104.40518318]
 [101.29326772

----------

## Activity 04: Use Pandas to compute the Mean, Median, and Variance

Ở bài này chúng ta sẽ làm quen với dataset ở kiểu dataframe trong Pandas

#### Loading the dataset

In [177]:
dataset = pd.read_csv('./data/world_population.csv', index_col=0)

In [178]:
# Hiển thị hai hàng đầu tiên của tập dữ liệu
dataset[0:2]

Country Code                                     Indicator Name  \
Country Name                                                                   
Aruba                 ABW  Population density (people per sq. km of land ...   
Andorra               AND  Population density (people per sq. km of land ...   

             Indicator Code  1960        1961        1962        1963  \
Country Name                                                            
Aruba           EN.POP.DNST   NaN  307.972222  312.366667  314.983333   
Andorra         EN.POP.DNST   NaN   30.587234   32.714894   34.914894   

                    1964        1965        1966  ...        2007        2008  \
Country Name                                      ...                           
Aruba         316.827778  318.666667  320.622222  ...  562.322222  563.011111   
Andorra        37.170213   39.470213   41.800000  ...  180.591489  182.161702   

                    2009        2010        2011        2012        2013  \
Country Name                                                               
Aruba         563.422222  564.427778  566.311111  568.850000  571.783333   
Andorra       181.859574  179.614894  175.161702  168.757447  161.493617   

                    2014        2015  2016  
Country Name                                
Aruba         574.672222  577.161111   NaN  
Andorra       154.863830  149.942553   NaN  

[2 rows x 60 columns]

---

#### Mean

In [180]:
# Mean của dòng thứ 3
dataset.iloc[[2]].mean(axis=1)

C:\Users\ngocl\AppData\Local\Temp\ipykernel_17364\2278954945.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  dataset.iloc[[2]].mean(axis=1)


Country Name
Afghanistan    25.373379
dtype: float64

In [181]:
# Mean của dòng cuối
dataset.iloc[[-1]].mean(axis=1)

C:\Users\ngocl\AppData\Local\Temp\ipykernel_17364\603836391.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  dataset.iloc[[-1]].mean(axis=1)


Country Name
Zimbabwe    24.520532
dtype: float64

In [182]:
# Tính mean của Germany
dataset.loc[["Germany"]].mean(axis=1)

C:\Users\ngocl\AppData\Local\Temp\ipykernel_17364\3194140693.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  dataset.loc[["Germany"]].mean(axis=1)


Country Name
Germany    227.773688
dtype: float64

**Ghi chú:**   
`.iloc()` và `.loc()` là hai phương thức quan trọng trong Pandas. Chúng cho phép thực hiện trích xuất dữ liệu chính xác dựa trên yêu cầu truyền vào hoặc số nguyên - dùng (`iloc`) hoặc cột cần tìm với (`loc`).

#### Median

In [184]:
# tính trung vị của hàng cuối cùng
dataset.iloc[[-1]].median(axis=1)

C:\Users\ngocl\AppData\Local\Temp\ipykernel_17364\2660172179.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  dataset.iloc[[-1]].median(axis=1)


Country Name
Zimbabwe    25.505431
dtype: float64

In [ ]:
# tính trung vị của 3 hàng cuối cùng
dataset[-3:].median(axis=1)

Country Name
Congo, Dem. Rep.    14.419050
Zambia              10.352668
Zimbabwe            25.505431
dtype: float64

In [ ]:
# Tình trung vị của 10 quốc gia đầu tiên
dataset.head(10).median(axis=1)

Country Name
Aruba                   348.022222
Andorra                 107.300000
Afghanistan              19.998926
Angola                    8.458253
Albania                 106.001058
Arab World               15.307283
United Arab Emirates     19.305072
Argentina                11.618238
Armenia                 105.898033
American Samoa          220.245000
dtype: float64

#### Variance

In [ ]:
# tính phương sai của 5 cột cuối
dataset.var().tail()

2012    3.063475e+06
2013    3.094597e+06
2014    3.157111e+06
2015    3.220634e+06
2016             NaN
dtype: float64

---

Thư viện Pandas có thể tương tác với một số tính năng của NumPy.

In [185]:
# Ví dụ về khả năng tương tác của NumPy Pandas khi tính mean
import numpy as np

print("Pandas", dataset["2015"].mean())
print("NumPy", np.mean(dataset["2015"]))

Pandas 368.70660104001837
NumPy 368.70660104001837


## Activity 05: Indexing, Slicing, and Iterating

> Chúng ta dùng tiếp dữ liệu `world_population.csv` của bài trên.

#### Indexing

In [186]:
# Hiển thị các dữ liệu thống kê của United States
dataset.loc[["United States"]].head()

Country Code                                     Indicator Name  \
Country Name                                                                    
United States          USA  Population density (people per sq. km of land ...   

              Indicator Code  1960      1961       1962       1963       1964  \
Country Name                                                                    
United States    EN.POP.DNST   NaN  20.05588  20.366723  20.661953  20.950959   

                    1965       1966  ...       2007       2008       2009  \
Country Name                         ...                                    
United States  21.214527  21.460952  ...  32.878611  33.243687  33.536399   

                    2010       2011       2012       2013       2014  \
Country Name                                                           
United States  33.817936  34.077243  34.337838  34.591983  34.863098   

                    2015  2016  
Country Name                    
United States  35.137648   NaN  

[1 rows x 60 columns]

In [ ]:
# Hiển thị quốc gia ở vị trí thứ 2 từ dưới đếm lên
dataset.iloc[[-2]]

Country Code                                     Indicator Name  \
Country Name                                                                   
Zambia                ZMB  Population density (people per sq. km of land ...   

             Indicator Code  1960      1961      1962      1963      1964  \
Country Name                                                                
Zambia          EN.POP.DNST   NaN  4.227724  4.359305  4.496824  4.639914   

                  1965      1966  ...        2007       2008       2009  \
Country Name                      ...                                     
Zambia        4.788452  4.942343  ...   17.135926  17.641587  18.170609   

                   2010       2011       2012       2013       2014      2015  \
Country Name                                                                    
Zambia        18.721585  19.294752  19.890745  20.508866  21.148177  21.80789   

              2016  
Country Name        
Zambia         NaN  

[1 rows x 60 columns]

In [ ]:
# Trích xuất cột thứ 2000 dưới dạng Series
dataset["2000"].head()

Country Name
Aruba          504.766667
Andorra        139.146809
Afghanistan     30.177894
Angola          12.078798
Albania        112.738212
Name: 2000, dtype: float64

In [ ]:
# Mật độ dân số của Ấn Độ năm 2000 (Dataframe)
dataset[["2000"]].loc[["India"]]

2000
Country Name            
India         354.326858

**Ghi chú:**
Trong quá trình truy xuất dữ liệu trên Pandas, chúng ta có thể dùng:
- Dấu ngoặc đơn `( ... )` để truy xuất một đối tượng cụ thể theo Series. Nó được sử dụng để chỉ định một phạm vi hoặc một tập hợp các chỉ mục hoặc cột xác định được.
- Còn khi sử dụng dấu ngoặc kép `"..."` tức là chúng ta muốn lấy các giá trị không xác định trong phạm vi cần xử lý.

Tóm lại, dấu (...) được sử dụng để chỉ định một phạm vi cụ thể, trong khi dấu "..." được sử dụng để chỉ định tất cả các giá trị trong phạm vi mà nó xuất hiện.

Để dễ hình dung, hãy so sánh code dưới đây và phía trên:

In [ ]:
# Mật độ dân số Ấn Độ năm 2000(Series)
dataset["2000"].loc["India"]

354.326858357522

---

#### Slicing

In [187]:
# Cắt ra các quốc gia từ dòng 2 đến 5
dataset.iloc[1:5]

Country Code                                     Indicator Name  \
Country Name                                                                   
Andorra               AND  Population density (people per sq. km of land ...   
Afghanistan           AFG  Population density (people per sq. km of land ...   
Angola                AGO  Population density (people per sq. km of land ...   
Albania               ALB  Population density (people per sq. km of land ...   

             Indicator Code  1960       1961       1962       1963       1964  \
Country Name                                                                    
Andorra         EN.POP.DNST   NaN  30.587234  32.714894  34.914894  37.170213   
Afghanistan     EN.POP.DNST   NaN  14.038148  14.312061  14.599692  14.901579   
Angola          EN.POP.DNST   NaN   4.305195   4.384299   4.464433   4.544558   
Albania         EN.POP.DNST   NaN  60.576642  62.456898  64.329234  66.209307   

                   1965       1966  ...        2007        2008        2009  \
Country Name                        ...                                       
Andorra       39.470213  41.800000  ...  180.591489  182.161702  181.859574   
Afghanistan   15.218206  15.545203  ...   39.637202   40.634655   41.674005   
Angola         4.624228   4.703271  ...   15.387749   15.915819   16.459536   
Albania       68.058066  69.874927  ...  108.394781  107.566204  106.843759   

                    2010        2011        2012        2013        2014  \
Country Name                                                               
Andorra       179.614894  175.161702  168.757447  161.493617  154.863830   
Afghanistan    42.830327   44.127634   45.533197   46.997059   48.444546   
Angola         17.020898   17.600302   18.196544   18.808215   19.433323   
Albania       106.314635  106.013869  105.848431  105.717226  105.607810   

                    2015  2016  
Country Name                    
Andorra       149.942553   NaN  
Afghanistan    49.821649   NaN  
Angola         20.070565   NaN  
Albania       105.444051   NaN  

[4 rows x 60 columns]

In [ ]:
# Cắt ra các dòng: Germany, Singapore, United States, and India 
dataset.loc[["Germany", "Singapore", "United States", "India"]]

Country Code                                     Indicator Name  \
Country Name                                                                    
Germany                DEU  Population density (people per sq. km of land ...   
Singapore              SGP  Population density (people per sq. km of land ...   
United States          USA  Population density (people per sq. km of land ...   
India                  IND  Population density (people per sq. km of land ...   

              Indicator Code  1960         1961         1962         1963  \
Country Name                                                                
Germany          EN.POP.DNST   NaN   210.172807   212.029284   214.001527   
Singapore        EN.POP.DNST   NaN  2540.895522  2612.238806  2679.104478   
United States    EN.POP.DNST   NaN    20.055880    20.366723    20.661953   
India            EN.POP.DNST   NaN   154.275864   157.424902   160.679256   

                      1964         1965         1966  ...          2007  \
Country Name                                          ...                 
Germany         215.731495   217.579970   219.403406  ...    235.943362   
Singapore      2748.656716  2816.268657  2887.164179  ...   6602.300719   
United States    20.950959    21.214527    21.460952  ...     32.878611   
India           164.029246   167.470047   170.995768  ...    396.774384   

                      2008         2009         2010         2011  \
Country Name                                                        
Germany         235.522178   234.939637   234.606908   234.673150   
Singapore      6913.422857  7125.104286  7231.811966  7363.193182   
United States    33.243687    33.536399    33.817936    34.077243   
India           402.621463   408.376922   414.028200   419.564848   

                      2012         2013         2014         2015  2016  
Country Name                                                             
Germany         230.750625   235.647997   232.347794   233.583362   NaN  
Singapore      7524.698300  7636.721358  7736.526167  7828.857143   NaN  
United States    34.337838    34.591983    34.863098    35.137648   NaN  
India           424.994581   430.345479   435.657171   440.957533   NaN  

[4 rows x 60 columns]

In [188]:
# Cắt ra các nước như Germany, Singapore, United States, and India với mật độ dân số của các nước đó trong các năm 1970, 1990, 2010
country_list = ["Germany", "Singapore", "United States", "India"]

dataset.loc[country_list][["1970", "1990", "2010"]]

1970         1990         2010
Country Name                                        
Germany         223.897371   227.517054   234.606908
Singapore      3096.268657  4547.958209  7231.811966
United States    22.388131    27.254514    33.817936
India           186.312757   292.817404   414.028200

---

#### Iterating

In [190]:
# sử dụng vòng lặp in name, country code và population trong các năm 1970, 1990 và 2010.
for index, row in dataset.iterrows():  
    print(index, '\n', row[["Country Code", "1970", "1990", "2010"]], '\n')

Aruba 
 Country Code           ABW
1970            328.138889
1990            345.266667
2010            564.427778
Name: Aruba, dtype: object 

Andorra 
 Country Code           AND
1970             51.657447
1990            115.980851
2010            179.614894
Name: Andorra, dtype: object 

Afghanistan 
 Country Code          AFG
1970            17.034429
1990            18.484162
2010            42.830327
Name: Afghanistan, dtype: object 

Angola 
 Country Code          AGO
1970             5.054118
1990              8.92586
2010            17.020898
Name: Angola, dtype: object 

Albania 
 Country Code           ALB
1970              77.93719
1990            119.946788
2010            106.314635
Name: Albania, dtype: object 

Arab World 
 Country Code          ARB
1970             8.964173
1990            16.303395
2010            25.923338
Name: Arab World, dtype: object 

United Arab Emirates 
 Country Code          ARE
1970             2.816196
1990            21.668158
2010     

Country Code          IRQ
1970            22.676411
1990            39.962629
2010             71.07238
Name: Iraq, dtype: object 

Iceland 
 Country Code         ISL
1970            2.039282
1990            2.541905
2010            3.172479
Name: Iceland, dtype: object 

Israel 
 Country Code           ISR
1970            137.430684
1990            215.341959
2010            352.292052
Name: Israel, dtype: object 

Italy 
 Country Code           ITA
1970            182.999048
1990             192.85043
2010            201.527902
Name: Italy, dtype: object 

Jamaica 
 Country Code           JAM
1970            172.576177
1990            220.683287
2010            248.460203
Name: Jamaica, dtype: object 

Jordan 
 Country Code          JOR
1970            18.753049
1990            38.060437
2010            73.416445
Name: Jordan, dtype: object 

Japan 
 Country Code           JPN
1970            284.551404
1990            338.828854
2010            351.309834
Name: Japan, dtype: object 

**Note:**   
Iterrows trả về một Series cho mỗi hàng. 

Điều này có nghĩa là nó không bảo toàn các kiểu dữ liệu trên hàng.

Nếu bạn cần bảo toàn kiểu dtype của các cột, hãy sử dụng phương thức `itertuples()`.

----

## Activity 06: Filtering, Sorting, and Reshaping

Vẫn giữ dataset `world_population.csv`.

In [191]:
# loading the Dataset
dataset = pd.read_csv('./data/world_population.csv', index_col=0)

#### Filtering

In [ ]:
# Lọc các cột 1961, 2000, 2015
dataset.filter(items=["1961", "2000", "2015"]).head()

1961        2000        2015
Country Name                                    
Aruba         307.972222  504.766667  577.161111
Andorra        30.587234  139.146809  149.942553
Afghanistan    14.038148   30.177894   49.821649
Angola          4.305195   12.078798   20.070565
Albania        60.576642  112.738212  105.444051

In [ ]:
# Lọc các quốc gia có mật độ dân số lớn hơn 500 vào năm 2000
dataset[(dataset["2000"] > 500)][["2000"]]

2000
Country Name                           
Aruba                        504.766667
Bangladesh                  1008.532988
Bahrain                      939.232394
Bermuda                     1236.660000
Barbados                     627.530233
Channel Islands              766.623711
Gibraltar                   2735.100000
Hong Kong SAR, China        6347.619048
Macao SAR, China           21595.350000
St. Martin (French part)     521.764706
Monaco                     16040.500000
Maldives                     953.333333
Malta                       1191.759375
Mauritius                    584.666502
Nauru                        502.100000
Singapore                   6011.771642
Sint Maarten (Dutch part)    897.617647

In [192]:
# Lọc từ năm 2000 trở đi
dataset.filter(regex="^2", axis=1).head()

2000        2001        2002        2003        2004  \
Country Name                                                               
Aruba         504.766667  516.077778  527.750000  538.972222  548.566667   
Andorra       139.146809  144.191489  151.161702  159.112766  166.674468   
Afghanistan    30.177894   31.448029   32.912231   34.475030   35.995236   
Angola         12.078798   12.483188   12.921871   13.388462   13.873025   
Albania       112.738212  111.685146  111.350730  110.934891  110.472226   

                    2005        2006        2007        2008        2009  \
Country Name                                                               
Aruba         555.727778  560.166667  562.322222  563.011111  563.422222   
Andorra       172.814894  177.389362  180.591489  182.161702  181.859574   
Afghanistan    37.373936   38.574296   39.637202   40.634655   41.674005   
Angola         14.368286   14.872437   15.387749   15.915819   16.459536   
Albania       109.908285  109.217044  108.394781  107.566204  106.843759   

                    2010        2011        2012        2013        2014  \
Country Name                                                               
Aruba         564.427778  566.311111  568.850000  571.783333  574.672222   
Andorra       179.614894  175.161702  168.757447  161.493617  154.863830   
Afghanistan    42.830327   44.127634   45.533197   46.997059   48.444546   
Angola         17.020898   17.600302   18.196544   18.808215   19.433323   
Albania       106.314635  106.013869  105.848431  105.717226  105.607810   

                    2015  2016  
Country Name                    
Aruba         577.161111   NaN  
Andorra       149.942553   NaN  
Afghanistan    49.821649   NaN  
Angola         20.070565   NaN  
Albania       105.444051   NaN

> **Chú ý:**
Dấu `^` được sử dụng để áp dụng một quy tắc regex chỉ cho phần đầu tiên của chuỗi. Nó chỉ khớp với chuỗi nếu chuỗi bắt đầu bằng mẫu regex cụ thể. Điều này cho phép bạn lọc ra các cột có tên bắt đầu bằng "2" từ DataFrame.

In [193]:
# Lọc các quốc gia có tên bắt đầu bằng `A`
dataset.filter(regex="^A", axis=0).head()

Country Code                                     Indicator Name  \
Country Name                                                                   
Aruba                 ABW  Population density (people per sq. km of land ...   
Andorra               AND  Population density (people per sq. km of land ...   
Afghanistan           AFG  Population density (people per sq. km of land ...   
Angola                AGO  Population density (people per sq. km of land ...   
Albania               ALB  Population density (people per sq. km of land ...   

             Indicator Code  1960        1961        1962        1963  \
Country Name                                                            
Aruba           EN.POP.DNST   NaN  307.972222  312.366667  314.983333   
Andorra         EN.POP.DNST   NaN   30.587234   32.714894   34.914894   
Afghanistan     EN.POP.DNST   NaN   14.038148   14.312061   14.599692   
Angola          EN.POP.DNST   NaN    4.305195    4.384299    4.464433   
Albania         EN.POP.DNST   NaN   60.576642   62.456898   64.329234   

                    1964        1965        1966  ...        2007        2008  \
Country Name                                      ...                           
Aruba         316.827778  318.666667  320.622222  ...  562.322222  563.011111   
Andorra        37.170213   39.470213   41.800000  ...  180.591489  182.161702   
Afghanistan    14.901579   15.218206   15.545203  ...   39.637202   40.634655   
Angola          4.544558    4.624228    4.703271  ...   15.387749   15.915819   
Albania        66.209307   68.058066   69.874927  ...  108.394781  107.566204   

                    2009        2010        2011        2012        2013  \
Country Name                                                               
Aruba         563.422222  564.427778  566.311111  568.850000  571.783333   
Andorra       181.859574  179.614894  175.161702  168.757447  161.493617   
Afghanistan    41.674005   42.830327   44.127634   45.533197   46.997059   
Angola         16.459536   17.020898   17.600302   18.196544   18.808215   
Albania       106.843759  106.314635  106.013869  105.848431  105.717226   

                    2014        2015  2016  
Country Name                                
Aruba         574.672222  577.161111   NaN  
Andorra       154.863830  149.942553   NaN  
Afghanistan    48.444546   49.821649   NaN  
Angola         19.433323   20.070565   NaN  
Albania       105.607810  105.444051   NaN  

[5 rows x 60 columns]

In [194]:
# Lọc các quốc gia có chứa từ "land"
dataset.filter(like="land", axis=0).head()

Country Code  \
Country Name                   
Switzerland              CHE   
Channel Islands          CHI   
Cayman Islands           CYM   
Finland                  FIN   
Faroe Islands            FRO   

                                                    Indicator Name  \
Country Name                                                         
Switzerland      Population density (people per sq. km of land ...   
Channel Islands  Population density (people per sq. km of land ...   
Cayman Islands   Population density (people per sq. km of land ...   
Finland          Population density (people per sq. km of land ...   
Faroe Islands    Population density (people per sq. km of land ...   

                Indicator Code  1960        1961        1962        1963  \
Country Name                                                               
Switzerland        EN.POP.DNST   NaN  137.479609  141.009285  144.056036   
Channel Islands    EN.POP.DNST   NaN  569.067010  574.551546  580.386598   
Cayman Islands     EN.POP.DNST   NaN   33.441667   33.925000   34.283333   
Finland            EN.POP.DNST   NaN   14.645934   14.745865   14.850484   
Faroe Islands      EN.POP.DNST   NaN   24.878223   25.181232   25.465616   

                       1964        1965        1966  ...        2007  \
Country Name                                         ...               
Switzerland      146.458915  148.160089  149.716707  ...  191.090115   
Channel Islands  586.484536  592.742268  599.103093  ...  806.783505   
Cayman Islands    34.579167   34.879167   35.175000  ...  214.500000   
Finland           14.933330   14.983197   15.039460  ...   17.391956   
Faroe Islands     25.749284   26.047994   26.363897  ...   34.813037   

                       2008        2009        2010        2011        2012  \
Country Name                                                                  
Switzerland      193.533632  195.966975  198.018752  200.232766  202.370204   
Channel Islands  812.304124  817.592784  839.910526  844.678947  849.136842   
Cayman Islands   220.520833  226.187500  231.287500  235.750000  239.675000   
Finland           17.484038   17.567855   17.648411   17.730995   17.815562   
Faroe Islands     34.834527   34.823066   34.790115   34.736390   34.665473   

                       2013        2014        2015  2016  
Country Name                                               
Switzerland      204.710649  207.223631  209.711914   NaN  
Channel Islands  853.357895  857.457895  861.536842   NaN  
Cayman Islands   243.204167  246.550000  249.862500   NaN  
Finland           17.897831   17.972003   18.039465   NaN  
Faroe Islands     34.593123   34.542264   34.526504   NaN  

[5 rows x 60 columns]

#### Sorting

In [ ]:
# sắp xếp các giá trị theo cột 1961
dataset.sort_values(by=["1961"])[["1961"]].head(10)

1961
Country Name                  
Greenland             0.098625
Mongolia              0.632212
Namibia               0.749775
Libya                 0.843320
Mauritania            0.856916
Botswana              0.946793
United Arab Emirates  1.207955
Australia             1.364565
Iceland               1.785825
Oman                  1.825186

In [ ]:
# sắp xếp các giá trị theo cột 2015
dataset.sort_values(by=["2015"])[["2015"]].head(10)

2015
Country Name          
Greenland     0.136713
Mongolia      1.904744
Namibia       2.986590
Australia     3.095579
Iceland       3.299980
Suriname      3.480609
Libya         3.568227
Guyana        3.896800
Canada        3.942567
Mauritania    3.946409

In [ ]:
# các giá trị được sắp xếp theo cột 2015 theo thứ tự giảm dần
dataset.sort_values(by=["2015"], ascending=False)[["2015"]].head(10)

2015
Country Name                      
Macao SAR, China      19392.937294
Monaco                18865.500000
Singapore              7828.857143
Hong Kong SAR, China   6957.809524
Gibraltar              3221.700000
Bahrain                1788.619481
Maldives               1363.876667
Malta                  1347.915625
Bermuda                1304.700000
Bangladesh             1236.810648

#### Reshaping

Để visualize thông tin vào năm 2015, ta cần tạo một tập hợp con của DataFrame chỉ chứa một hàng chứa tất cả các giá trị cho năm 2015 được ánh xạ tới mã quốc gia dưới dạng cột.

Ý tưởng phác thảo như sau:
```
Country Code    ABW    AFG    AGO   ...
----------------------------------------
        2015    577     49     20   ...
```

In [ ]:
# reshaping năm 2015 dưới dạng hàng và mã quốc gia dưới dạng cột
dataset_2015 = dataset[["Country Code", "2015"]]

dataset_2015.pivot(index=["2015"] * len(dataset_2015), columns="Country Code", values="2015")

Country Code         ABW        AFG        AGO         ALB         AND  \
2015          577.161111  49.821649  20.070565  105.444051  149.942553   

Country Code        ARB        ARE        ARG         ARM     ASM    ...      \
2015          28.779858  109.53305  15.864696  105.996207  277.69    ...       

Country Code     VGB         VIR         VNM        VUT        WLD        WSM  \
2015          200.78  295.925714  295.751927  21.710582  56.627369  68.278445   

Country Code        YEM        ZAF       ZMB        ZWE  
2015          50.821477  45.303251  21.80789  40.332819  

[1 rows x 264 columns]

---

## Exercise 01: Loading a sample dataset and calculating the mean.

#### Loading our dataset: Vẫn dùng lại data của normal_distribution

In [ ]:
dataset

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 , 106.1472841 ,  95.08715803],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034,
         89.03452725,  96.2832753 , 104.60344836, 101.13442416],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901,
        106.39798503,  95.46493436,  94.35373179, 106.83273763],
       [ 96.02548256, 102.82360856, 106.47551845, 101.34745901,
        102.45651798,  98.7476749

---

#### After loading our dataset

In [ ]:
# Check shape
dataset.shape

(24, 8)

In [ ]:
#Tính mean của dòng đầu tiên
np.mean(dataset[0])

100.177647525

In [ ]:
# calculating the mean for the first column
np.mean(dataset[:, 0])

99.76743510416668

In [ ]:
# mean for each row
np.mean(dataset, axis=1)

array([100.17764752,  97.27899259, 100.20466135, 100.56785907,
       100.98341406,  97.83018578, 101.49052285,  99.75332252,
       101.89845125,  99.77973914, 101.013081  , 100.54961696,
        98.48256886,  98.49816126, 101.85956927,  97.05201872,
       102.62147483, 101.21177037,  99.58777968,  98.96533534,
       103.85792812, 101.89050288,  99.07192574,  99.34233101])

In [ ]:
# mean for each col
np.mean(dataset, axis=0)

array([ 99.7674351 ,  99.61229127, 101.14584656, 101.8449316 ,
        99.04871791,  99.67838931,  99.7848489 , 100.44049274])

In [ ]:
# calculating the mean for the whole matrix
np.mean(dataset)

100.16536917390624

When looking at the mean values we can really nicely see the effect of calculating the mean of several vaules taken from a normal distribution.   
If we had even more data we would get even close to 100.